name: build

on:
  push: 
   branches: 
    - 'master'        
  # workflow_dispatch: 
  pull_request:  
  
env:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    name: build
    uses: mrganeshkudale/backend-api/.github/workflows/build.yml@main
    secrets: inherit
    with:
      java-version: 8
        
